USE NAODB;
DELIMITER //

CREATE PROCEDURE ADD_USER_ADDRESS 
(IN PID_USERNAME INT
,IN PCOUNTRY_CODE VARCHAR(5)
,IN PZIPCODE INT
,IN PADDRESS_1 VARCHAR(200)
,IN PADDRESS_2 VARCHAR(200)
,IN PRECEPTOR_NAME VARCHAR(200)
,IN PPHONE_NUMBER VARCHAR(10)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SELECT 'Error' AS status;
    END;

    INSERT INTO NAODB.USER_ADDRESS 
    (ID_USERNAME
    ,COUNTRY_CODE
    ,ZIPCODE
    ,ADDRESS_1
    ,ADDRESS_2
    ,RECEPTOR_NAME
    ,PHONE_NUMBER)
    VALUES 
    (PID_USERNAME
    ,PCOUNTRY_CODE
    ,PZIPCODE
    ,PADDRESS_1
    ,PADDRESS_2
    ,PRECEPTOR_NAME
    ,PPHONE_NUMBER);

    SELECT 'Success' AS status;
END //

DELIMITER ;
