USE NAODB;
DELIMITER //

CREATE PROCEDURE DELETE_USER_ADDRESS 
(IN PID INT
,IN PID_USERNAME INT)
BEGIN
    DECLARE UPDATE_COUNT INT DEFAULT 0;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 'Error' AS status;
    END;
    
    START TRANSACTION;

    UPDATE NAODB.USER_ADDRESS 
    SET IS_ACTIVE = 0
    ,UPDATE_DATE = NOW()
    WHERE ID = PID
    AND ID_USERNAME = PID_USERNAME;

    SET UPDATE_COUNT = ROW_COUNT();

    IF UPDATE_COUNT = 1 THEN
        COMMIT;
        SELECT 'Success' AS status;
    ELSE
        ROLLBACK;
        SELECT 'Failure' AS status;
    END IF;
END //

DELIMITER ;
