USE NAODB;
DELIMITER //

CREATE PROCEDURE GET_USER_ADDRESSES(IN PID_USERNAME INT)
BEGIN
    SELECT ID
    ,ID_USERNAME
    ,COUNTRY_CODE
    ,ZIPCODE
    ,ADDRESS_1
    ,ADDRESS_2
    ,RECEPTOR_NAME
    ,PHONE_NUMBER
    FROM NAODB.USER_ADDRESS
    WHERE ID_USERNAME = PID_USERNAME
    AND IS_ACTIVE = 1;
END //

DELIMITER ;
