USE NAODB;
DELIMITER //

CREATE PROCEDURE UPDATE_USER_ADDRESS 
(IN PID INT
,IN PID_USERNAME INT
,IN PCOUNTRY_CODE VARCHAR(5)
,IN PZIPCODE INT
,IN PADDRESS_1 VARCHAR(200)
,IN PADDRESS_2 VARCHAR(200)
,IN PRECEPTOR_NAME VARCHAR(200)
,IN PPHONE_NUMBER VARCHAR(10))
BEGIN
    DECLARE NEW_ID INT;
    DECLARE INSERT_COUNT INT DEFAULT 0;
    DECLARE UPDATE_COUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 'Error' AS status;
    END;

    START TRANSACTION;

    INSERT INTO NAODB.USER_ADDRESS 
    (ID_USERNAME
    ,COUNTRY_CODE
    ,ZIPCODE
    ,ADDRESS_1
    ,ADDRESS_2
    ,RECEPTOR_NAME
    ,PHONE_NUMBER
    ,PREVIOUS_ID
    ,CREATION_DATE
    ,UPDATE_DATE)
    SELECT ID_USERNAME
    ,COUNTRY_CODE
    ,ZIPCODE
    ,ADDRESS_1
    ,ADDRESS_2
    ,RECEPTOR_NAME
    ,PHONE_NUMBER
    ,PID
    ,NOW()
    ,NOW()
    FROM NAODB.USER_ADDRESS
    WHERE ID = PID
    AND ID_USERNAME = PID_USERNAME;

    SET NEW_ID = LAST_INSERT_ID();
    SET UPDATE_COUNT = ROW_COUNT();

    UPDATE NAODB.USER_ADDRESS 
    SET IS_ACTIVE = 0
    ,UPDATE_DATE = NOW()
    WHERE ID = PID
	AND ID_USERNAME = PID_USERNAME;

    SET INSERT_COUNT = ROW_COUNT();

    UPDATE NAODB.USER_ADDRESS 
    SET ID_USERNAME = IFNULL(PID_USERNAME, ID_USERNAME)
    ,COUNTRY_CODE = IFNULL(PCOUNTRY_CODE, COUNTRY_CODE)
    ,ZIPCODE = IFNULL(PZIPCODE, ZIPCODE)
    ,ADDRESS_1 = IFNULL(PADDRESS_1, ADDRESS_1)
    ,ADDRESS_2 = IFNULL(PADDRESS_2, ADDRESS_2)
    ,RECEPTOR_NAME = IFNULL(PRECEPTOR_NAME, RECEPTOR_NAME)
    ,PHONE_NUMBER = IFNULL(PPHONE_NUMBER, PHONE_NUMBER)
    WHERE ID = NEW_ID
	AND ID_USERNAME = PID_USERNAME;

    IF INSERT_COUNT = 1 AND UPDATE_COUNT = 1 THEN
        COMMIT;
        SELECT 'Success' AS status;
    ELSE
        ROLLBACK;
        SELECT 'Failure' AS status;
    END IF;
END //

DELIMITER ;
