USE NAODB;

CREATE TABLE `PROPERTY` (
  `CODE` VARCHAR(100),
  `VALUE` VARCHAR(200),
  `DESCRIPTION` VARCHAR(400)
);

INSERT INTO NAODB.PROPERTY (CODE,VALUE,DESCRIPTION)
VALUES
('ADDRESS_LIMIT','5','MAXIMAS DIRECCIONES POR USUARIO');