USE NAODB;

CREATE TABLE `USER_ADDRESS` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_USERNAME` INT NOT NULL,
  `IS_ACTIVE` INT DEFAULT 1,
  `COUNTRY_CODE` VARCHAR(5) NOT NULL,
  `ZIPCODE` INT NOT NULL,
  `ADDRESS_1` VARCHAR(200) NOT NULL,
  `ADDRESS_2` VARCHAR(200),
  `RECEPTOR_NAME` VARCHAR(200) NOT NULL,
  `PHONE_NUMBER` VARCHAR(10) NOT NULL,
  FOREIGN KEY (`ID_USERNAME`) REFERENCES AUTH.USER(ID)
);

CREATE INDEX IDX_ADDRESS ON USER_ADDRESS (ID_USERNAME, IS_ACTIVE);
CREATE INDEX IDX_HIST ON USER_ADDRESS (PREVIOUS_ID);

ALTER TABLE USER_ADDRESS ADD COLUMN `PREVIOUS_ID` INT UNIQUE NULL;
ALTER TABLE USER_ADDRESS ADD COLUMN `CREATION_DATE` DATETIME DEFAULT NOW();
ALTER TABLE USER_ADDRESS ADD COLUMN `UPDATE_DATE` DATETIME;
